[package]
name = "siteblocker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
http = "0.2.9"
third-wheel = "0.6.0"
tokio = "1.29.1"
